// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnfB8OH_pf29oJmYjESSx3vu0jxCcGn3k',
    appId: '1:195006949017:web:34c6972335c7d567b07a08',
    messagingSenderId: '195006949017',
    projectId: 'looplab-50d1d',
    authDomain: 'looplab-50d1d.firebaseapp.com',
    storageBucket: 'looplab-50d1d.firebasestorage.app',
    measurementId: 'G-Y9MDZZDKMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2UK-kpiEd-mJA1qR4YoVrDdEaGXtjlo0',
    appId: '1:195006949017:android:8a0ce435c3e52863b07a08',
    messagingSenderId: '195006949017',
    projectId: 'looplab-50d1d',
    storageBucket: 'looplab-50d1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASJZSxAURxMJ-4PaoTwtFksUhw0X-Ii4s',
    appId: '1:195006949017:ios:772209314a156c7ab07a08',
    messagingSenderId: '195006949017',
    projectId: 'looplab-50d1d',
    storageBucket: 'looplab-50d1d.firebasestorage.app',
    iosBundleId: 'com.example.loopLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASJZSxAURxMJ-4PaoTwtFksUhw0X-Ii4s',
    appId: '1:195006949017:ios:772209314a156c7ab07a08',
    messagingSenderId: '195006949017',
    projectId: 'looplab-50d1d',
    storageBucket: 'looplab-50d1d.firebasestorage.app',
    iosBundleId: 'com.example.loopLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnfB8OH_pf29oJmYjESSx3vu0jxCcGn3k',
    appId: '1:195006949017:web:86ce501360d7938db07a08',
    messagingSenderId: '195006949017',
    projectId: 'looplab-50d1d',
    authDomain: 'looplab-50d1d.firebaseapp.com',
    storageBucket: 'looplab-50d1d.firebasestorage.app',
    measurementId: 'G-JZ3FEFPNFN',
  );
}
